// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulePayrollBlazor.Data;

#nullable disable

namespace SchedulePayrollBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116090000_AddPayrollModule")]
    partial class AddPayrollModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("EmploymentTypeValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employment_type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("job_title");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.EmployeeComponent", b =>
                {
                    b.Property<int>("EmployeeComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_component_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeComponentId"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("PayComponentId")
                        .HasColumnType("int")
                        .HasColumnName("pay_component_id");

                    b.HasKey("EmployeeComponentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayComponentId");

                    b.ToTable("employee_components", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.EmployeeCompensation", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal?>("FixedMonthlySalary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fixed_monthly_salary");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsHourly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hourly");

                    b.HasKey("EmployeeId");

                    b.ToTable("employee_compensation", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.EmployeeProfile", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthdate");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hire_date");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("employee_profiles", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayComponent", b =>
                {
                    b.Property<int>("PayComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pay_component_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayComponentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<decimal?>("DefaultRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("default_rate");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("PayComponentId");

                    b.ToTable("pay_components", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayPeriod", b =>
                {
                    b.Property<int>("PayPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pay_period_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayPeriodId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("period_name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("PayPeriodId");

                    b.ToTable("pay_periods", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("label");

                    b.Property<int>("PayrollEntryId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_entry_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PayrollEntryId");

                    b.ToTable("payroll_adjustments", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollLine", b =>
                {
                    b.Property<int>("PayrollLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payroll_line_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollLineId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("PayComponentId")
                        .HasColumnType("int")
                        .HasColumnName("pay_component_id");

                    b.Property<int>("PayrollRunId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_run_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rate");

                    b.HasKey("PayrollLineId");

                    b.HasIndex("PayComponentId");

                    b.HasIndex("PayrollRunId");

                    b.ToTable("payroll_lines", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_pay");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("calculated_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_pay");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_period_id");

                    b.Property<decimal>("TotalBonuses")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_bonuses");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_deductions");

                    b.Property<decimal>("TotalHoursWorked")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_hours_worked");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId");

                    b.ToTable("payroll_entries", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("payroll_periods", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollRun", b =>
                {
                    b.Property<int>("PayrollRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payroll_run_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollRunId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_pay");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_pay");

                    b.Property<int>("PayPeriodId")
                        .HasColumnType("int")
                        .HasColumnName("pay_period_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_deductions");

                    b.HasKey("PayrollRunId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayPeriodId");

                    b.ToTable("payroll_runs", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("shift_date");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("employee_name");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("group_name");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.TimeLog", b =>
                {
                    b.Property<int>("TimeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("time_log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TimeLogId"));

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("clock_in");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("clock_out");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.HasKey("TimeLogId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("time_logs", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Employee", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("SchedulePayrollBlazor.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.EmployeeComponent", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithMany("EmployeeComponents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulePayrollBlazor.Data.Models.PayComponent", "PayComponent")
                        .WithMany("EmployeeComponents")
                        .HasForeignKey("PayComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayComponent");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.EmployeeCompensation", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithOne("Compensation")
                        .HasForeignKey("SchedulePayrollBlazor.Data.Models.EmployeeCompensation", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.EmployeeProfile", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithOne("Profile")
                        .HasForeignKey("SchedulePayrollBlazor.Data.Models.EmployeeProfile", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulePayrollBlazor.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollLine", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.PayComponent", "PayComponent")
                        .WithMany("PayrollLines")
                        .HasForeignKey("PayComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulePayrollBlazor.Data.Models.PayrollRun", "PayrollRun")
                        .WithMany("PayrollLines")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayComponent");

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollAdjustment", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.PayrollEntry", "PayrollEntry")
                        .WithMany("Adjustments")
                        .HasForeignKey("PayrollEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollEntry");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollRun", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithMany("PayrollRuns")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulePayrollBlazor.Data.Models.PayPeriod", "PayPeriod")
                        .WithMany("PayrollRuns")
                        .HasForeignKey("PayPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayPeriod");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollEntry", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithMany("PayrollEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulePayrollBlazor.Data.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("Entries")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Schedule", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.TimeLog", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Employee", "Employee")
                        .WithMany("TimeLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.User", b =>
                {
                    b.HasOne("SchedulePayrollBlazor.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Employee", b =>
                {
                    b.Navigation("EmployeeComponents");

                    b.Navigation("Compensation");

                    b.Navigation("PayrollRuns");

                    b.Navigation("PayrollEntries");

                    b.Navigation("Profile");

                    b.Navigation("Schedules");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayComponent", b =>
                {
                    b.Navigation("EmployeeComponents");

                    b.Navigation("PayrollLines");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayPeriod", b =>
                {
                    b.Navigation("PayrollRuns");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollEntry", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollRun", b =>
                {
                    b.Navigation("PayrollLines");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.PayrollPeriod", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SchedulePayrollBlazor.Data.Models.User", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
